### ISSUE TITLE
Suggestion - Display all simulated spell casts on a timeline 

### ISSUE THREAD

**Issue by randomdude163** [Cheesehyvel/magesim-tbc2#12]
To make it more clear what spells are used when during the simulation, display all spell casts or even all simulation steps on a timeline. You could make this option toggleable.

I am talking about something like this:

```
Scorch -> Scorch -> ... -> Fireball -> Fireball -> ... -> Evocation -> ... -> Mana Gem -> ...
0.0s      1.5s      ...    7.5s        10.5s       ...    52.5s        ...    85.0s       ...
```

BTW: Love your sim, great work! Can I donate somehow?

**Comment by Cheesehyvel** [comment]
You can see all this if you do a single run and click on "Combat log" button under the dps.

**Comment by Cheesehyvel** [comment]
> BTW: Love your sim, great work! Can I donate somehow?
Thanks man, no donations needed :)

**Comment by randomdude163** [comment]
> 
> 
> You can see all this if you do a single run and click on "Combat log" button under the dps.

I feel stupid. Sorry, I guess I could have found this by digging a little more... 😆
