### ISSUE TITLE
Add a custom item entry option

### ISSUE THREAD

**Issue by Ataraxey2** [Cheesehyvel/magesim-tbc2#19]
There are a number of items, both from classic, quests, and other areas like heroics that are not currently supported. Additionally adding a custom item entry system for each gear slot will allow easier modeling for specific stat sets. 

There could likely just be a line at the bottom that allows stats to be entered on each line along with a name.

Is this possible to be added?

**Comment by Cheesehyvel** [comment]
95c4b97
