### ISSUE TITLE
Moonkin and Judgement of Crusader Crit added twice

### ISSUE THREAD

**Issue by quasexort** [Cheesehyvel/magesim-tbc2#2]
Moonkin aura and Judgement of Crusader are counted twice.  Both show up in player.h and in simulation.h  

https://github.com/Cheesehyvel/magesim-tbc2/blob/6ac0ea9649f19b14c0112dac37643046517b10f1/src/simulation.h#L1077-L1080

https://github.com/Cheesehyvel/magesim-tbc2/blob/6ac0ea9649f19b14c0112dac37643046517b10f1/src/player.h#L169-L172

**Comment by Cheesehyvel** [comment]
Fixed
10d47dc
