### ISSUE TITLE
Frost spec is misleading

### ISSUE THREAD

**Issue by chaodhib** [Cheesehyvel/magesim-tbc2#26]
Hi hi. First of all: thank you for this great tool!

Onto the issue: I think what the sim calls "frost" spec is misleading. The tool is just using the [Arcane 40/0/21 spec](https://tbc.wowhead.com/talent-calc/mage/2500052300030150330125--053500031003001) and spamming frostbolt on it. We should rename/reword it in the way to make it clear that the [PvE Frost 18/0/43 spec](https://tbc.wowhead.com/talent-calc/mage/230005230003--0535000310230012250551) is not being used here. And instead, mentions that it is the Arcane spec with Frostbolt spamming.

On a side note, it would be nice to add full support for the PvE Frost 18/0/43 spec. But I guess adding a water elemental simulation would involve non trivial changes to the code.

**Comment by Cheesehyvel** [comment]
Water elemental is not in the sim because
1. It takes a long time to split the code to work with pets
2. We don't have the actual numbers for all the stats of the water elemental.

I won't change the name of the spec since that option only changes which spells to use (frostbolt).
I might add a disclaimer that water ele isn't supported.

**Comment by chaodhib** [comment]
> I won't change the name of the spec since that option only changes which spells to use (frostbolt)

Yeah but that's source of the confusion imho. Why name the sim's "frost" spec this way when is actually not using the [PvE Frost 18/0/43 spec](https://tbc.wowhead.com/talent-calc/mage/230005230003--0535000310230012250551), it's using the [Arcane 40/0/21 spec](https://tbc.wowhead.com/talent-calc/mage/2500052300030150330125--053500031003001), like the "arcane" spec of the sim. Both the "arcane" and the "frost" spec are using 40/0/21 but with a different spell rotation.

**Comment by avicennax** [comment]
@Cheesehyvel - I'm currently playing around with code to add a water elemental. My thinking was that we could just sample the water elem waterbolt stats and fit an appropriate distribution offline and sample from it during online. I've read in various places that the elem's stats may scale with the mage's stats - not sure if that true or if you know better but I was going to test the hypothesis in any event.

**Comment by Cheesehyvel** [comment]
It does scale. We have some numbers but not all of them.
I've asked in mage discord a couple of times but no one seems to have the complete information.
Which means any implementation will probably be inaccurate and misleading.

**Comment by avicennax** [comment]
What are some of those numbers we know? I'm not convinced the situation is as dire as you might imply. You're already using estimated resistances from TBC Beta from WCL (per code comments). Base stat scaling (int) should be extremely easy to estimate. I haven't looked at the data yet but my hunch is that if I pulled ~200 Kara logs we'd be able to make some decent enough assumptions about scaling such that the water elem's sim behavior would be statistically indistinguishable from the observations - we/I can always iterate from there. I'll poke around on the mage discord and look into some logs today.

**Comment by Cheesehyvel** [comment]
The only confirmed data point is water bolt coefficient which seems to be 0.25 of the mages sp, which can also be calculated as 30% sp * 0.833 coefficient.
We're missing base and scaling data for mana/crit/hit.
We also need documented behavior of how the buffs in the sim affect the elemental, like BL/drums/jc neck/totems etc.
The elemental also seems to have a delay between casts which needs to be factored in.

Feel free to gather this data. I just don't care enough about frost spec to do it myself.
