### ISSUE TITLE
Fire Mage 4PC T5 not working

### ISSUE THREAD

**Issue by Notfaith** [Cheesehyvel/magesim-tbc2#34]
4PC T5 isn't working for fire mages

Spellfire Gloves = 2018.66 DPS
Stat Weights=
10 Int = 1.99
10 SP/Fire SP = 9.56
10 Crit = 6.62

Tirisfal Gloves = 1998.27 (giving 4 set)

Difference in Items
27 SP (assuming 2 reds) = 25.812 DPS
-4 Crit = -2.648 DPS
-17 Int = -3.383

Spellfire Gloves without 4 set should be = 19.781, Result is 20.39 showing 4set isn't calculating or has 0% uptime
[https://i.imgur.com/d7acDny.png](url)
[https://i.imgur.com/Jj6wLV0.png](url)
[https://i.imgur.com/Vd6sNgh.png](url)

Arcane Madness is the buff that you should gain (can beseen working for arcane in last picture)

**Comment by Cheesehyvel** [comment]
15b9e08
