### ISSUE TITLE
Darkmoon Card: Crusade

### ISSUE THREAD

**Issue by silverwind** [Cheesehyvel/magesim-tbc2#41]
[Darkmoon Card: Crusade](https://tbc.wowhead.com/item=31856/darkmoon-card-crusade) is coming in phase 2, it'd be nice to have it modeled. Stacks increase on every direct damage event, e.g. dots only increase once but AM stacks on every individual hit.

**Comment by Cheesehyvel** [comment]
It's already in the sim but marked as phase 3.
Any confirmed it's coming in phase 2?

**Comment by silverwind** [comment]
They are confirmed per https://old.reddit.com/r/classicwow/comments/owyb9l/tbc_darkmoon_cards_coming_in_phase_2/h7j31th/.
