### ISSUE TITLE
Leg sockets persist when changing selected item

### ISSUE THREAD

**Issue by bryanbt** [Cheesehyvel/magesim-tbc2#52]
how to reproduce:

go to the "Legs" menu
choose Trial-Fire Trousers
select 3x Great Dawnstone
Change equipped item to Spellstrike Pants
Change 3x Great Dawnstone to any other gem combination.
re-equip Trial-Fire Trousers.
your old gem selection has been replaced.
equip Legwraps of the Aldor (no gem sockets)
click Equipped Items Overview
it shows the Legwraps of the Aldor with whatever 3 gems you had previously set. (this part seems to only be a visual bug and not impacting the sims)

it makes it confusing when comparing items since you may not realize the gem choice is universal to the leg slot.

**Comment by Cheesehyvel** [comment]
Cannot reproduce.
