### ISSUE TITLE
[Discussion] Support for custom rotations/actions.

### ISSUE THREAD

**Issue by Cheesehyvel** [Cheesehyvel/magesim-tbc2#57]
**The problem**
The original purpose of the sim was to find gear upgrades for arcane mages based on simple parameters and "standard" play for short-medium long fights. 
It has now grown and people use it for all specs and to learn about rotations, cooldowns, buffs, talents etc.
With this growth people want to be able to have more control of the decision making part of the sim, ie the rotation and when to use cooldowns, get innervates etc.
Up til now I have simply added more preset rotations and more config options. But this can't go on forever. The more options we get the more likely it is that there will be a conflict and these options won't go together well. This is also a problem for new/casual players who are just trying to find out what gear to get and get confused/intimidated by the vast amount of options.

**Solution**
Let the user have (almost) full control of the "player" in the sim while having common presets for the average user to choose from.
For this I have two possible solutions. One is more flexible but easier to get wrong, while the other is less flexible and a little bit clunkier but you can't mess up in the same way.
The buffs/debuffs etc will still stay the same. We're only talking about rotations and maybe in-combat cooldowns/buffs.

**Solution 1: Lua scripts**
The rotation is a lua script that returns the next spell to cast. It has access to functions to check for mana, fight duration, buff/debuff durations, stats, etc. It can also set local variables to keep track of rotations.
We could also look into the possibility of something similar for cooldowns and external buffs (like innervate/tide/pi etc).
This is very flexible but can also be intimidating for people that can't code.

**Solution 2: Fixed rules and actions**
Instead of a script we take the common checks/rules and add them to a dropdown. We make it possible to combine these with AND/OR statements to finally decide which spell to cast if all the checks pass.
This could easily become quite heavy with many inputs but protects the user from misspelling functions or variables.

**Discussion**
Please give me your thoughts on this matter. 
Which solution do you prefer? Or maybe you have a different solution you would like to propose?

**Comment by Savari94** [comment]
I do agree if this gets to complex alot of users will have a hard time with getting the correct information out of the sim. I think the buff and CDs sections are good enough to achieve 99% of what people want to know and only the rotation section needs work. Some version of solution 2 I think would work best. Im not good at coding so I dont know if this is possible with how you have coded your sim but here is what I envision: 
The filler spell section gets changed to 2 or 3 different dropdowns with individual standard mage spells you can choose from and the number of times to cast it.
Filler Rotation:
[Spell #1] cast [x] times
[Spell #2] cast [x] times
[Spell #3] cast [x] times
Force Arcane Blast stack reset by casting the spell in the lowest populated row: yes [ ] no [ ]

I think that would solve 95% of the stuff people want. If you want to add slightly more complication you can support CREAM by hard coding a CRAEM Arcane Misses (+30%crit) as one of spells in the dropdown and adding a check box to do a filler rotation after clear cast except during arcane power. 

The rest could stay the same. If people want to experiment with not dropping Arcane Blast stacks all they have to do is pick the spells they want, make sure the force Arcane Blast stack reset isnt checked and maybe adjust the start regen rotaion to a little higher mana %.  To keep it the same as your sim does it now you would pick Frostbolt in spell #1 from the dropdown and have it cast 3 times with the force AB stack reset checked.

**Comment by Cheesehyvel** [comment]
I should add the one of the reasons I wanted a more flexible solution came when I was looking into an aoe mode, which opened a can of worms when it came to rotations. Flamestrike ranks, AE, blast wave, dragons breath, cone of cold, blizzard, just so many options on how to use them and when to use what.
