### ISSUE TITLE
Stat Weight variance

### ISSUE THREAD

**Issue by jdelvare** [Cheesehyvel/magesim-tbc2#58]
Thank you for the wonderful simulation tool.

One thing which I think could be improved is the Stat Weight computations. Currently, there's a lot of variance from one run to the next, so much that the numbers can't really be used for anything. These numbers can even be nonsensical at times, for example adding a stat resulting in lower DPS (that is, this stats gets rated negatively) or a stat which we know has no effect (like +Fire SP for an Arcane-Frost rotation) being given a non-zero weight. This is clearly the result of the significant variance from one simulation run to the next.

Specifically, I'm interested in the relative values of +Int and +SP, as I believe this is at the heart of optimizing the Arcane Mage DPS. Unfortunately, one Stat Weight comparison run tells me +Int is only 6.6% more valuable than +SP, while the next run tells me +int is 26.4% more valuable than +SP. This is a huge difference that will result in opposite decisions being made. For example, in the first case I'd use +9 SP gems, while in the second case I would use +8 Int gems.

I tried enabling the "Use average spell damage" option to minimize the variance, but that did not actually help. I suppose most of the variance comes from the Spell Crit chances (and Spell miss to a lesser degree).

For this specific computation to be useful, I think you need to take a different approach. Instead of temporarily applying the stat change then running a new batch of simulations, I believe you want to run the very same simulation(s) with the modified stat. So whatever is random during the simulation would have the very same outcome, first without, and then with, the modified stat. This would factor out all the variance caused by RNG. Or, is this easier to implement, these comparisons should be run with average values for everything that normally involves random. For example, instead of Crit Chance being a random factor for each spell, the damage of each spell would be computed as (1 - Crit%)*(average non-crit damage) + (Crit%)*(average crit damage). Again the idea being to void out the random factors which create so much variance, leaving only the actual stat change to measure.

In essence, this is quite similar to the "Use average spell damage" option, just extended to more random factors. While this diverges significantly from the original design of the tool (running many simulations with each of them being as "real" as possible), I believe this would serve the purpose much better, when it comes to evaluating the weight of individual stats.

**Comment by Cheesehyvel** [comment]
Just set the RNG seed in the config to a non-zero value.

**Comment by jdelvare** [comment]
Oh, much better indeed after setting the RNG seed to 42. Thank you very much for the tip and sorry for reporting a non-bug.
In order to prevent other users from doing the same mistake, maybe it would make sense to write down that hint on the Stat Weight tab? Or even have a field directly on that tab to access the seed setting. My point is that running the simulator on this tab with full RNG is actually a waste of time and resources, as the results can't be trusted.
Thanks again.
