### ISSUE TITLE
Mana Regen using Spirit as MP5 equivalent.

### ISSUE THREAD

**Issue by bphelpsjr** [Cheesehyvel/magesim-tbc2#6]
The following line seems incorrect, and if it is incorrect is overvaluing Spirit in the Simulation.
mps+= while_casting * spi;

According to https://wowwiki-archive.fandom.com/wiki/Spirit, the formula should be the following at Lvl 70.
Mana Regen = 5 * (0.001 + sqrt(Int) * Spirit * 0.009327) * 0.60  (rounded up) (*Note the .6 here is not the Mage Armor + Aracane Meditation)

**Comment by Cheesehyvel** [comment]
The spirit based mana regen is currently the formula you posted without the 0.6 at the end.
That 0.6 has no reliable source. The source cited in your link doesn't mention the 0.6 and has just magically appeared in the wowwiki article.
The current formula without the 0.6 is also confirmed on the beta.

The cited post:
https://web.archive.org/web/20080401233141/http://elitistjerks.com:80/634066-post55.html

The basis for the post:
https://web.archive.org/web/20080401233146/http://elitistjerks.com/635940-post114.html
