### ISSUE TITLE
Gems and Socket Boni not working fine.

### ISSUE THREAD

**Issue by FaLu93** [Cheesehyvel/magesim-tbc2#67]
Mantle of Tirisfal and Belt of Blasting have the same Socket Boni.
When I take the Socket Boni in my Belt i got more DPS...
eg. 2x 8int in Shoulder and 1x 8int and 1x sp-stam in belt is less dps than reversed

my sim:

eyJlcXVpcHBlZCI6eyJ3ZWFwb24iOjI5OTg4LCJvZmZfaGFuZCI6bnVsbCwicmFuZ2VkIjoyODc4MywiaGVhZCI6MzAyMDYsIm5lY2siOjMwMDE1LCJzaG91bGRlciI6MzAyMTAsImJhY2siOjI4NzY2LCJjaGVzdCI6MzAxOTYsIndyaXN0IjozMjU4NiwiaGFuZHMiOjI5OTg3LCJ3YWlzdCI6MzAwMzgsImxlZ3MiOjMwMjA3LCJmZWV0IjozMjIzOSwiZmluZ2VyMSI6MjkyODcsImZpbmdlcjIiOjI5MzAzLCJ0cmlua2V0MSI6MjkzNzAsInRyaW5rZXQyIjoyODcyN30sImVuY2hhbnRzIjp7IndlYXBvbiI6Mjc5ODEsIm9mZl9oYW5kIjpudWxsLCJyYW5nZWQiOm51bGwsImhlYWQiOjM1NDQ3LCJuZWNrIjpudWxsLCJzaG91bGRlciI6MzU0MDYsImJhY2siOjI1MDg0LCJjaGVzdCI6Mjc5NjAsIndyaXN0IjoyNzkxNywiaGFuZHMiOjMzOTk3LCJ3YWlzdCI6bnVsbCwibGVncyI6MzEzNzIsImZlZXQiOjM0MDA4LCJmaW5nZXIxIjoyNzkyNCwiZmluZ2VyMiI6Mjc5MjQsInRyaW5rZXQxIjpudWxsLCJ0cmlua2V0MiI6bnVsbH0sImdlbXMiOnsid2VhcG9uIjpbbnVsbCxudWxsLG51bGxdLCJvZmZfaGFuZCI6W251bGwsbnVsbCxudWxsXSwicmFuZ2VkIjpbbnVsbCxudWxsLG51bGxdLCJoZWFkIjpbMzQyMjAsMjQwNDcsbnVsbF0sIm5lY2siOltudWxsLG51bGwsbnVsbF0sInNob3VsZGVyIjpbMjQwNDcsMjQwNDcsbnVsbF0sImJhY2siOltudWxsLG51bGwsbnVsbF0sImNoZXN0IjpbMjQwNDcsMjQwNDcsMzA1ODZdLCJ3cmlzdCI6W251bGwsbnVsbCxudWxsXSwiaGFuZHMiOltudWxsLG51bGwsbnVsbF0sIndhaXN0IjpbMjQwNDcsMjQwNTYsbnVsbF0sImxlZ3MiOlsyNDA0NyxudWxsLG51bGxdLCJmZWV0IjpbMjQwNDcsMjQwNDcsbnVsbF0sImZpbmdlcjEiOltudWxsLG51bGwsbnVsbF0sImZpbmdlcjIiOltudWxsLG51bGwsbnVsbF0sInRyaW5rZXQxIjpbbnVsbCxudWxsLG51bGxdLCJ0cmlua2V0MiI6W251bGwsbnVsbCxudWxsXX0sImNvbmZpZyI6eyJpdGVyYXRpb25zIjoxMDAwMDAsInJhY2UiOjUsInNoYXR0X2ZhY3Rpb24iOjEsImR1cmF0aW9uIjoxODAsImR1cmF0aW9uX3ZhcmlhbmNlIjowLCJybmdfc2VlZCI6MCwiZ2NkX3VubG9ja2VkIjpmYWxzZSwiYXZnX3NwZWxsX2RtZyI6ZmFsc2UsImFkZGl0aW9uYWxfZGF0YSI6ZmFsc2UsInRhcmdldHMiOjEsIm1pc2VyeSI6dHJ1ZSwiY3Vyc2Vfb2ZfZWxlbWVudHMiOnRydWUsIm1hbGVkaWN0aW9uIjp0cnVlLCJqdWRnZW1lbnRfb2ZfdGhlX2NydXNhZGVyIjpmYWxzZSwianVkZ2VtZW50X29mX3dpc2RvbSI6dHJ1ZSwidmFtcGlyaWNfdG91Y2giOnRydWUsInZhbXBpcmljX3RvdWNoX3JlZ2VuIjo1MCwidG90ZW1fb2Zfd3JhdGgiOmZhbHNlLCJ3cmF0aF9vZl9haXIiOnRydWUsIm1hbmFfc3ByaW5nIjp0cnVlLCJpbXByb3ZlZF9tYW5hX3NwcmluZyI6dHJ1ZSwiYXJjYW5lX2ludGVsbGVjdCI6dHJ1ZSwiZGl2aW5lX3NwaXJpdCI6dHJ1ZSwiaW1wcm92ZWRfZGl2aW5lX3NwaXJpdCI6dHJ1ZSwiYmxlc3Npbmdfb2Zfa2luZ3MiOnRydWUsImJsZXNzaW5nX29mX3dpc2RvbSI6dHJ1ZSwibWFya19vZl90aGVfd2lsZCI6dHJ1ZSwibW9vbmtpbl9hdXJhIjpmYWxzZSwibWFnZV9hcm1vciI6dHJ1ZSwibW9sdGVuX2FybW9yIjpmYWxzZSwiaW5zcGlyaW5nX3ByZXNlbmNlIjpmYWxzZSwiZmlyZV92dWxuZXJhYmlsaXR5IjpmYWxzZSwibWFpbnRhaW5fZmlyZV92dWxuZXJhYmlsaXR5IjpmYWxzZSwid2ludGVyc19jaGlsbCI6ZmFsc2UsImltcF9zYW5jdGl0eSI6ZmFsc2UsImZlcm9jaW91c19pbnNwaXJhdGlvbiI6MCwiZm9vZCI6Mjc2NTcsImZsYXNrIjowLCJiYXR0bGVfZWxpeGlyIjoyODEwMywiZ3VhcmRpYW5fZWxpeGlyIjozMjA2Nywid2VhcG9uX29pbCI6MjA3NDksImRydW1zIjowLCJkcnVtc19mcmllbmQiOmZhbHNlLCJwb3Rpb24iOjIyODMyLCJjb25qdXJlZCI6MjIwNDQsImF0aWVzaF9tYWdlIjpmYWxzZSwiYXRpZXNoX3dhcmxvY2siOmZhbHNlLCJleWVfb2ZfdGhlX25pZ2h0IjpmYWxzZSwiY2hhaW5fb2ZfdGhlX3R3aWxpZ2h0X293bCI6ZmFsc2UsImphZGVfcGVuZGFudF9vZl9ibGFzdGluZyI6ZmFsc2UsInNjcm9sbF9vZl9zcGlyaXQiOmZhbHNlLCJrcmVlZ3MiOnRydWUsImJsb29kdGhpc3RsZSI6ZmFsc2UsInNjb3VyZ2ViYW5lIjpmYWxzZSwidGlyaXNmYWxfMnNldCI6dHJ1ZSwidGlyaXNmYWxfNHNldCI6dHJ1ZSwidGVtcGVzdF8yc2V0IjpmYWxzZSwidGVtcGVzdF80c2V0IjpmYWxzZSwic3BlbGxmaXJlX3NldCI6ZmFsc2UsInNwZWxsc3RyaWtlX3NldCI6ZmFsc2UsImV0ZXJuYWxfc2FnZSI6ZmFsc2UsIndyYXRoX29mX2NlbmFyaXVzIjpmYWxzZSwiYmxhZGVfb2Zfd2l6YXJkcnkiOmZhbHNlLCJyb2JlX2VsZGVyX3NjcmliZXMiOmZhbHNlLCJibGFkZV9vZl9ldGVybmFsX2RhcmtuZXNzIjpmYWxzZSwic3Vud2VsbF9uZWNrX2FsZG9yIjpmYWxzZSwic3Vud2VsbF9uZWNrX3NjcnllciI6ZmFsc2UsIm1hbmFfZXRjaGVkXzRzZXQiOmZhbHNlLCJtZXRhX2dlbSI6MzQyMjAsInRyaW5rZXQxIjoyOTM3MCwidHJpbmtldDIiOjI4NzI3LCJpbm5lcnZhdGUiOjEsIm1hbmFfdGlkZSI6dHJ1ZSwiYmxvb2RsdXN0Ijp0cnVlLCJwb3dlcl9pbmZ1c2lvbiI6ZmFsc2UsInN5bWJvbF9vZl9ob3BlIjpmYWxzZSwibWFpbl9yb3RhdGlvbiI6MCwicmVnZW5fcm90YXRpb24iOjAsInJlZ2VuX21hbmFfYXQiOjIwLCJyZWdlbl9zdG9wX2F0IjozMCwicmVnZW5fYWJfY291bnQiOjMsImFiX2hhc3RlX3N0b3AiOjAsImZpcmVfYmxhc3Rfd2VhdmUiOnRydWUsImNjX2FtX3F1ZXVlIjpmYWxzZSwiY2NfYW1fcmVwZWF0IjpmYWxzZSwidHJpbmtldDFfdCI6WzEsbnVsbCxudWxsLG51bGxdLCJ0cmlua2V0Ml90IjpbMSxudWxsLG51bGwsbnVsbF0sImFyY2FuZV9wb3dlcl90IjpbMSxudWxsLG51bGwsbnVsbF0sInByZXNlbmNlX29mX21pbmRfdCI6WzAsbnVsbCxudWxsLG51bGxdLCJpY3lfdmVpbnNfdCI6WzEsIiIsbnVsbCxudWxsXSwiY29sZF9zbmFwX3QiOls0MCxudWxsLG51bGwsbnVsbF0sImNvbWJ1c3Rpb25fdCI6W251bGwsbnVsbCxudWxsLG51bGxdLCJiZXJzZXJraW5nX3QiOltudWxsLG51bGwsbnVsbCxudWxsXSwibWFuYV90aWRlX3QiOls3MCxudWxsLG51bGwsbnVsbF0sImJsb29kbHVzdF90IjpbMSxudWxsLG51bGwsbnVsbF0sInBvd2VyX2luZnVzaW9uX3QiOltudWxsLG51bGwsbnVsbCxudWxsXSwiZHJ1bXNfdCI6W251bGwsbnVsbCxudWxsLG51bGxdLCJpbm5lcnZhdGVfdCI6W251bGwsbnVsbCxudWxsLG51bGxdLCJwb3Rpb25fdCI6WzEsbnVsbCxudWxsLG51bGxdLCJjb25qdXJlZF90IjpbMTAsbnVsbCxudWxsLG51bGxdLCJzeW1ib2xfb2ZfaG9wZV9hdCI6MCwiZXZvY2F0aW9uX2F0Ijo0MCwiZXZvX3RpY2tzIjowLCJ0YWxlbnRzIjoiaHR0cHM6Ly90YmMud293aGVhZC5jb20vdGFsZW50LWNhbGMvbWFnZS8yNTAwMjUwMzAwMDMwMTUwMzMwMTI1LS0wNTM1MDAwMzEwMDMwMDEiLCJzdGF0cyI6eyJpbnRlbGxlY3QiOjYxNSwic3Bpcml0IjoyOTMsIm1wNSI6MCwiY3JpdCI6MTUuMTMxMDE0NDkyNzUzNjI1LCJoaXQiOjYuODkzODE5MzM0Mzg5ODU4LCJoYXN0ZSI6MS43NzU1MjMxNDUyMTI0Mjg3LCJzcGVsbF9wb3dlciI6OTQ1LCJzcGVsbF9wb3dlcl9hcmNhbmUiOjUwLCJzcGVsbF9wb3dlcl9mcm9zdCI6MCwic3BlbGxfcG93ZXJfZmlyZSI6NTB9LCJ0b29sdGlwcyI6ZmFsc2V9fQ==

**Comment by Cheesehyvel** [comment]
Cannot reproduce.
Make sure you put the gems in the right slots.
