### ISSUE TITLE
Double check coding.

### ISSUE THREAD

**Issue by Savari94** [Cheesehyvel/magesim-tbc2#70]
There was some discussion on the mage discord that Sextant of Unstable Currents was simming higher then it should in aoe conditions especially when aoe capped. Can you please double check that the proc is is coded as the right stat. There was some speculation that it was proccing crit and not spell power.

Also the 2% damage from improved sanc aura sims higher than the 3% damage from Ferocious Inspiration which shouldn't be the case unless the math for the 2 is applied at different levels. Idk for sure but something to double check and make sure it is correct.

**Comment by Cheesehyvel** [comment]
lmao yeah it was adding crit
probably sloppy reading from me when I added the first 20 trinkets
