### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Savari94** [Cheesehyvel/magesim-tbc2#74]
Can you add Frostbolt rank 11 x3 to the arcane filler list. Its is the lowest rank of frostbolt that doesn't have a down rank penalty. Based on some of the math I've done its mana efficiency to dps ratio is better than max rank frostbolt. There is a good chance it leads to a dps increase so it would be cool to try it out.

**Comment by Cheesehyvel** [comment]
Shouldn't r11 have a penalty?
Downrank = (spell_maxlevel + 6) / playerlevel
r11 is level 60-62, which means the downrank coefficient should be 68/70.

**Comment by Savari94** [comment]
That's what I thought too but its actually Downrank = (spell_maxlevel + 10) / playerlevel. I was able to test this using the addon found [here ](https://github.com/coolmodi/SpellCalc#:~:text=A%20WoW%20classic%20addon%20that,current%20stats%20of%20your%20character.). It uses the +10 equation and calculates a spell damage stats based on your current stats. I tested by spamming on Dr. Boom and make sure the actually damage never fell below what the addon calculated as the minimum damage of the spell. After testing the actual spell damage never fell below what the addon said was the minimum damage of the spell. If the game used the +6 equation the spell power coefficient would be lower than what the addon says and I'd be getting damage values lower than the what the addon reported I should be getting.

**Comment by Savari94** [comment]
Ok did some more testing on other classes and I wasn't getting the same results as I was getting on my mage and dug a little deeper. I found out yes it technically (spell_maxlevel + 6) / playerlevel. If you onto wow head tbc you can move the level slider on the spells and for the first few level after it is learned it gains base damage. The last level that the spell gains base damage is its max level. For mage spells this is 4 levels after the spell is learned. So anything learned at lvl 60 or higher has no down rank penalty. For other classes it was different though. I only looked at dps spells but Shamans, Warlocks, and Priest spells gain base damage for 5 lvls and Druids for 6 lvls.
