### ISSUE TITLE
Cold Snap usage does not reset Icy Veins CD

### ISSUE THREAD

**Issue by lambrech** [Cheesehyvel/magesim-tbc2#76]
When I simulate DPS with a cold snap talent (e.g. the deault arcane talent build) Icy Veins will be used the second time 3 minutes after the frist usage, even if I use Cold Snap after the frist usage of Icy Veins

Steps to reproduce:
Import config provided below which uses Icy Veins at 10sec, Cold Snap at 11 sec (this can also be seen in combat log).

The second usage of Icy Veins should be at 30sec but it will get used after 190sec.

Would be awesome if you could implement this.

eyJlcXVpcHBlZCI6eyJ3ZWFwb24iOjMyMzc0LCJvZmZfaGFuZCI6bnVsbCwicmFuZ2VkIjoyODc4MywiaGVhZCI6MzAyMDYsIm5lY2siOjMwMDE1LCJzaG91bGRlciI6MzAyMTAsImJhY2siOjMyNTI0LCJjaGVzdCI6MzAxOTYsIndyaXN0IjozMDg3MCwiaGFuZHMiOjMwMjA1LCJ3YWlzdCI6MzA4ODgsImxlZ3MiOjMxMDU4LCJmZWV0IjozMjIzOSwiZmluZ2VyMSI6MjkzMDUsImZpbmdlcjIiOjMyNTI3LCJ0cmlua2V0MSI6MzI0ODMsInRyaW5rZXQyIjozMDcyMH0sImVuY2hhbnRzIjp7IndlYXBvbiI6Mjc5ODEsIm9mZl9oYW5kIjpudWxsLCJyYW5nZWQiOm51bGwsImhlYWQiOjM1NDQ3LCJuZWNrIjpudWxsLCJzaG91bGRlciI6Mjk0NjcsImJhY2siOm51bGwsImNoZXN0IjoyNzk2MCwid3Jpc3QiOjI3OTE3LCJoYW5kcyI6MzM5OTcsIndhaXN0IjpudWxsLCJsZWdzIjozMTM3MiwiZmVldCI6MzQwMDgsImZpbmdlcjEiOjI3OTI0LCJmaW5nZXIyIjoyNzkyNCwidHJpbmtldDEiOm51bGwsInRyaW5rZXQyIjpudWxsfSwiZ2VtcyI6eyJ3ZWFwb24iOltudWxsLG51bGwsbnVsbF0sIm9mZl9oYW5kIjpbbnVsbCxudWxsLG51bGxdLCJyYW5nZWQiOltudWxsLG51bGwsbnVsbF0sImhlYWQiOlszNDIyMCwzMjIwNCxudWxsXSwibmVjayI6W251bGwsbnVsbCxudWxsXSwic2hvdWxkZXIiOlszMDU1MSwzMDYwMCxudWxsXSwiYmFjayI6W251bGwsbnVsbCxudWxsXSwiY2hlc3QiOlszMjIwNCwzMjIwNCwzMDU4Nl0sIndyaXN0IjpbMzIyMDQsbnVsbCxudWxsXSwiaGFuZHMiOltudWxsLG51bGwsbnVsbF0sIndhaXN0IjpbMzIyMDQsMzIyMDQsbnVsbF0sImxlZ3MiOlszMjIwNCxudWxsLG51bGxdLCJmZWV0IjpbMzIyMDQsMzIyMDQsbnVsbF0sImZpbmdlcjEiOltudWxsLG51bGwsbnVsbF0sImZpbmdlcjIiOltudWxsLG51bGwsbnVsbF0sInRyaW5rZXQxIjpbbnVsbCxudWxsLG51bGxdLCJ0cmlua2V0MiI6W251bGwsbnVsbCxudWxsXX0sImNvbmZpZyI6eyJpdGVyYXRpb25zIjozMDAwMCwicmFjZSI6Mywic2hhdHRfZmFjdGlvbiI6MCwiZHVyYXRpb24iOjIxMCwiZHVyYXRpb25fdmFyaWFuY2UiOjAsInJuZ19zZWVkIjowLCJnY2RfdW5sb2NrZWQiOmZhbHNlLCJhdmdfc3BlbGxfZG1nIjpmYWxzZSwiYWRkaXRpb25hbF9kYXRhIjpmYWxzZSwidGFyZ2V0cyI6MSwibWlzZXJ5Ijp0cnVlLCJjdXJzZV9vZl9lbGVtZW50cyI6dHJ1ZSwibWFsZWRpY3Rpb24iOmZhbHNlLCJqdWRnZW1lbnRfb2ZfdGhlX2NydXNhZGVyIjp0cnVlLCJqdWRnZW1lbnRfb2Zfd2lzZG9tIjpmYWxzZSwidmFtcGlyaWNfdG91Y2giOnRydWUsInZhbXBpcmljX3RvdWNoX3JlZ2VuIjo1NSwidG90ZW1fb2Zfd3JhdGgiOnRydWUsIndyYXRoX29mX2FpciI6dHJ1ZSwibWFuYV9zcHJpbmciOnRydWUsImltcHJvdmVkX21hbmFfc3ByaW5nIjpmYWxzZSwiYXJjYW5lX2ludGVsbGVjdCI6dHJ1ZSwiZGl2aW5lX3NwaXJpdCI6ZmFsc2UsImltcHJvdmVkX2RpdmluZV9zcGlyaXQiOmZhbHNlLCJibGVzc2luZ19vZl9raW5ncyI6dHJ1ZSwiYmxlc3Npbmdfb2Zfd2lzZG9tIjp0cnVlLCJtYXJrX29mX3RoZV93aWxkIjp0cnVlLCJtb29ua2luX2F1cmEiOmZhbHNlLCJtYWdlX2FybW9yIjp0cnVlLCJtb2x0ZW5fYXJtb3IiOmZhbHNlLCJpbnNwaXJpbmdfcHJlc2VuY2UiOnRydWUsImZpcmVfdnVsbmVyYWJpbGl0eSI6ZmFsc2UsIm1haW50YWluX2ZpcmVfdnVsbmVyYWJpbGl0eSI6dHJ1ZSwid2ludGVyc19jaGlsbCI6ZmFsc2UsImltcF9zYW5jdGl0eSI6ZmFsc2UsImZlcm9jaW91c19pbnNwaXJhdGlvbiI6MCwiZm9vZCI6Mjc2NTcsImZsYXNrIjoxMzUxMSwiYmF0dGxlX2VsaXhpciI6MCwiZ3VhcmRpYW5fZWxpeGlyIjowLCJ3ZWFwb25fb2lsIjoyMjUyMiwiZHJ1bXMiOjAsImRydW1zX2ZyaWVuZCI6ZmFsc2UsInBvdGlvbiI6MjI4MzIsImNvbmp1cmVkIjoyMjA0NCwiYXRpZXNoX21hZ2UiOmZhbHNlLCJhdGllc2hfd2FybG9jayI6ZmFsc2UsImV5ZV9vZl90aGVfbmlnaHQiOmZhbHNlLCJjaGFpbl9vZl90aGVfdHdpbGlnaHRfb3dsIjpmYWxzZSwiamFkZV9wZW5kYW50X29mX2JsYXN0aW5nIjpmYWxzZSwic2Nyb2xsX29mX3NwaXJpdCI6ZmFsc2UsImtyZWVncyI6ZmFsc2UsImJsb29kdGhpc3RsZSI6ZmFsc2UsInNjb3VyZ2ViYW5lIjpmYWxzZSwidGlyaXNmYWxfMnNldCI6dHJ1ZSwidGlyaXNmYWxfNHNldCI6dHJ1ZSwidGVtcGVzdF8yc2V0IjpmYWxzZSwidGVtcGVzdF80c2V0IjpmYWxzZSwic3BlbGxmaXJlX3NldCI6ZmFsc2UsInNwZWxsc3RyaWtlX3NldCI6ZmFsc2UsImV0ZXJuYWxfc2FnZSI6dHJ1ZSwid3JhdGhfb2ZfY2VuYXJpdXMiOmZhbHNlLCJibGFkZV9vZl93aXphcmRyeSI6ZmFsc2UsInJvYmVfZWxkZXJfc2NyaWJlcyI6ZmFsc2UsImJsYWRlX29mX2V0ZXJuYWxfZGFya25lc3MiOmZhbHNlLCJzdW53ZWxsX25lY2tfYWxkb3IiOmZhbHNlLCJzdW53ZWxsX25lY2tfc2NyeWVyIjpmYWxzZSwibWFuYV9ldGNoZWRfNHNldCI6ZmFsc2UsIm1ldGFfZ2VtIjozNDIyMCwidHJpbmtldDEiOjMyNDgzLCJ0cmlua2V0MiI6MzA3MjAsImlubmVydmF0ZSI6MCwibWFuYV90aWRlIjpmYWxzZSwiYmxvb2RsdXN0Ijp0cnVlLCJwb3dlcl9pbmZ1c2lvbiI6ZmFsc2UsInN5bWJvbF9vZl9ob3BlIjpmYWxzZSwibWFpbl9yb3RhdGlvbiI6MCwicmVnZW5fcm90YXRpb24iOjAsInJlZ2VuX21hbmFfYXQiOjUwLCJyZWdlbl9zdG9wX2F0Ijo4NSwicmVnZW5fYWJfY291bnQiOjMsImFiX2hhc3RlX3N0b3AiOjAsImZpcmVfYmxhc3Rfd2VhdmUiOmZhbHNlLCJjY19hbV9xdWV1ZSI6ZmFsc2UsImNjX2FtX3JlcGVhdCI6ZmFsc2UsImJpc19hc2h0b25ndWUiOmZhbHNlLCJ0cmlua2V0MV90IjpbMTAsbnVsbCxudWxsLG51bGxdLCJ0cmlua2V0Ml90IjpbbnVsbCxudWxsLG51bGwsbnVsbF0sImFyY2FuZV9wb3dlcl90IjpbMTAsbnVsbCxudWxsLG51bGxdLCJwcmVzZW5jZV9vZl9taW5kX3QiOltudWxsLG51bGwsbnVsbCxudWxsXSwiaWN5X3ZlaW5zX3QiOlsxMCwzMCxudWxsLG51bGxdLCJjb2xkX3NuYXBfdCI6WzExLG51bGwsbnVsbCxudWxsXSwiY29tYnVzdGlvbl90IjpbMTAsbnVsbCxudWxsLG51bGxdLCJiZXJzZXJraW5nX3QiOltudWxsLG51bGwsbnVsbCxudWxsXSwibWFuYV90aWRlX3QiOlsxMjAsbnVsbCxudWxsLG51bGxdLCJibG9vZGx1c3RfdCI6WzEwLG51bGwsbnVsbCxudWxsXSwicG93ZXJfaW5mdXNpb25fdCI6W251bGwsbnVsbCxudWxsLG51bGxdLCJkcnVtc190IjpbbnVsbCxudWxsLG51bGwsbnVsbF0sImlubmVydmF0ZV90IjpbMTIwLG51bGwsbnVsbCxudWxsXSwicG90aW9uX3QiOltudWxsLG51bGwsbnVsbCxudWxsXSwiY29uanVyZWRfdCI6WzE1LG51bGwsbnVsbCxudWxsXSwic3ltYm9sX29mX2hvcGVfYXQiOjAsImV2b2NhdGlvbl9hdCI6MCwiZXZvX3RpY2tzIjowLCJ0YWxlbnRzIjoiaHR0cHM6Ly90YmMud293aGVhZC5jb20vdGFsZW50LWNhbGMvbWFnZS8yNTAwMjUwMzAwMDMwMTUwMzMwMTI1LS0wNTM1MDAwMzEwMDMwMDEiLCJzdGF0cyI6eyJpbnRlbGxlY3QiOjYyNywic3Bpcml0IjozMTIsIm1wNSI6MCwiY3JpdCI6MTYuMTcyNjgxMTU5NDIwMjksImhpdCI6NS45NDI5NDc3MDIwNjAyMjMsImhhc3RlIjo3LjQ4MjU2MTgyNjI1MjM3OCwic3BlbGxfcG93ZXIiOjEwMDUsInNwZWxsX3Bvd2VyX2FyY2FuZSI6NTAsInNwZWxsX3Bvd2VyX2Zyb3N0IjowLCJzcGVsbF9wb3dlcl9maXJlIjo1MCwiY3JpdF9yYXRpbmciOjMzNywiaGl0X3JhdGluZyI6NzUsImhhc3RlX3JhdGluZyI6MTE4fSwidG9vbHRpcHMiOmZhbHNlfX0=

**Comment by Cheesehyvel** [comment]
Cold snap uses icy veins instantly since that is it's only purpose.

**Comment by lambrech** [comment]
That is actually not 100% true. If you use Cold Snap while Icy Veins is still active, Icy Veins will not be recasted.
But I do understand now, that the "workaround" (or maybe intended behavior) is to use Cold Snap after the first Icy Veins ran out.

Thank you for pointin me in that direction - this is a really awesome simulator!
