### ISSUE TITLE
Bug?: The Skull of Gul'dan

### ISSUE THREAD

**Issue by DieterSc** [Cheesehyvel/magesim-tbc2#78]
Hey,

I think there is a Bug with the "The Skull of Gul'dan". It always sims worse than "Icon of the Silver Crescent". Even though it does the same thing...just better.

![grafik](https://user-images.githubusercontent.com/103314137/162568750-eebc7ade-5ef6-4a19-9a19-2d2e280f552d.png)

Or am I missing something?

BTW, I love your Simulator. I use it a lot, Great work!

Heres my export:
eyJlcXVpcHBlZCI6eyJ3ZWFwb24iOjMwOTEwLCJvZmZfaGFuZCI6MzA4NzIsInJhbmdlZCI6MzMxOTIsImhlYWQiOjMwMjA2LCJuZWNrIjoyODc2Miwic2hvdWxkZXIiOjMwMjEwLCJiYWNrIjoyODc5NywiY2hlc3QiOjMwMTk2LCJ3cmlzdCI6MzA4NzAsImhhbmRzIjozMDIwNSwid2Fpc3QiOjMwMDM4LCJsZWdzIjozMDkxNiwiZmVldCI6MzIyMzksImZpbmdlcjEiOjI5MzA1LCJmaW5nZXIyIjozMjUyNywidHJpbmtldDEiOjMwNjI2LCJ0cmlua2V0MiI6MzgyOTB9LCJlbmNoYW50cyI6eyJ3ZWFwb24iOjI3OTc1LCJvZmZfaGFuZCI6bnVsbCwicmFuZ2VkIjpudWxsLCJoZWFkIjozNTQ0NywibmVjayI6bnVsbCwic2hvdWxkZXIiOjM1NDM3LCJiYWNrIjpudWxsLCJjaGVzdCI6Mjc5NjAsIndyaXN0IjozNDAwMSwiaGFuZHMiOjMzOTk3LCJ3YWlzdCI6bnVsbCwibGVncyI6MzEzNzIsImZlZXQiOjM0MDA4LCJmaW5nZXIxIjoyNzkyNCwiZmluZ2VyMiI6Mjc5MjQsInRyaW5rZXQxIjpudWxsLCJ0cmlua2V0MiI6bnVsbH0sImdlbXMiOnsid2VhcG9uIjpbbnVsbCxudWxsLG51bGxdLCJvZmZfaGFuZCI6W251bGwsbnVsbCxudWxsXSwicmFuZ2VkIjpbMzIyMjUsbnVsbCxudWxsXSwiaGVhZCI6WzM0MjIwLDMyMjA0LG51bGxdLCJuZWNrIjpbbnVsbCxudWxsLG51bGxdLCJzaG91bGRlciI6WzMyMjA0LDMyMjI1LG51bGxdLCJiYWNrIjpbbnVsbCxudWxsLG51bGxdLCJjaGVzdCI6WzMyMjA0LDMyMjA0LDMyMjI1XSwid3Jpc3QiOlszMjIwNCxudWxsLG51bGxdLCJoYW5kcyI6W251bGwsbnVsbCxudWxsXSwid2Fpc3QiOlsyNDA0NywyNDA0NyxudWxsXSwibGVncyI6WzMyMjA0LDMyMjA0LDMyMjI1XSwiZmVldCI6WzMyMjA0LDMyMjI1LG51bGxdLCJmaW5nZXIxIjpbbnVsbCxudWxsLG51bGxdLCJmaW5nZXIyIjpbbnVsbCxudWxsLG51bGxdLCJ0cmlua2V0MSI6W251bGwsbnVsbCxudWxsXSwidHJpbmtldDIiOltudWxsLG51bGwsbnVsbF19LCJjb25maWciOnsiaXRlcmF0aW9ucyI6MzAwMDAsInJhY2UiOjIsInNoYXR0X2ZhY3Rpb24iOjEsImR1cmF0aW9uIjoyMTAsImR1cmF0aW9uX3ZhcmlhbmNlIjowLCJybmdfc2VlZCI6MCwiZ2NkX3VubG9ja2VkIjpmYWxzZSwiYXZnX3NwZWxsX2RtZyI6ZmFsc2UsImFkZGl0aW9uYWxfZGF0YSI6ZmFsc2UsInRhcmdldHMiOjEsIm1pc2VyeSI6dHJ1ZSwiY3Vyc2Vfb2ZfZWxlbWVudHMiOnRydWUsIm1hbGVkaWN0aW9uIjpmYWxzZSwianVkZ2VtZW50X29mX3RoZV9jcnVzYWRlciI6ZmFsc2UsImp1ZGdlbWVudF9vZl93aXNkb20iOnRydWUsInZhbXBpcmljX3RvdWNoIjp0cnVlLCJ2YW1waXJpY190b3VjaF9yZWdlbiI6NDUsInRvdGVtX29mX3dyYXRoIjp0cnVlLCJ3cmF0aF9vZl9haXIiOnRydWUsIm1hbmFfc3ByaW5nIjp0cnVlLCJpbXByb3ZlZF9tYW5hX3NwcmluZyI6ZmFsc2UsImFyY2FuZV9pbnRlbGxlY3QiOnRydWUsImRpdmluZV9zcGlyaXQiOnRydWUsImltcHJvdmVkX2RpdmluZV9zcGlyaXQiOmZhbHNlLCJibGVzc2luZ19vZl9raW5ncyI6dHJ1ZSwiYmxlc3Npbmdfb2Zfd2lzZG9tIjp0cnVlLCJtYXJrX29mX3RoZV93aWxkIjp0cnVlLCJtb29ua2luX2F1cmEiOmZhbHNlLCJtYWdlX2FybW9yIjp0cnVlLCJtb2x0ZW5fYXJtb3IiOmZhbHNlLCJpbnNwaXJpbmdfcHJlc2VuY2UiOnRydWUsImZpcmVfdnVsbmVyYWJpbGl0eSI6ZmFsc2UsIm1haW50YWluX2ZpcmVfdnVsbmVyYWJpbGl0eSI6dHJ1ZSwid2ludGVyc19jaGlsbCI6ZmFsc2UsImltcF9zYW5jdGl0eSI6ZmFsc2UsImZlcm9jaW91c19pbnNwaXJhdGlvbiI6MCwiZm9vZCI6Mjc2NTcsImZsYXNrIjoxMzUxMiwiYmF0dGxlX2VsaXhpciI6MCwiZ3VhcmRpYW5fZWxpeGlyIjowLCJ3ZWFwb25fb2lsIjoyMDc0OSwiZHJ1bXMiOjAsImRydW1zX2ZyaWVuZCI6dHJ1ZSwicG90aW9uIjoyMjgzMiwiY29uanVyZWQiOjIyMDQ0LCJhdGllc2hfbWFnZSI6ZmFsc2UsImF0aWVzaF93YXJsb2NrIjpmYWxzZSwiZXllX29mX3RoZV9uaWdodCI6ZmFsc2UsImNoYWluX29mX3RoZV90d2lsaWdodF9vd2wiOmZhbHNlLCJqYWRlX3BlbmRhbnRfb2ZfYmxhc3RpbmciOmZhbHNlLCJzY3JvbGxfb2Zfc3Bpcml0IjpmYWxzZSwia3JlZWdzIjp0cnVlLCJibG9vZHRoaXN0bGUiOmZhbHNlLCJzY291cmdlYmFuZSI6ZmFsc2UsInRpcmlzZmFsXzJzZXQiOnRydWUsInRpcmlzZmFsXzRzZXQiOnRydWUsInRlbXBlc3RfMnNldCI6ZmFsc2UsInRlbXBlc3RfNHNldCI6ZmFsc2UsInNwZWxsZmlyZV9zZXQiOmZhbHNlLCJzcGVsbHN0cmlrZV9zZXQiOmZhbHNlLCJldGVybmFsX3NhZ2UiOnRydWUsIndyYXRoX29mX2NlbmFyaXVzIjpmYWxzZSwiYmxhZGVfb2Zfd2l6YXJkcnkiOmZhbHNlLCJyb2JlX2VsZGVyX3NjcmliZXMiOmZhbHNlLCJibGFkZV9vZl9ldGVybmFsX2RhcmtuZXNzIjpmYWxzZSwic3Vud2VsbF9uZWNrX2FsZG9yIjpmYWxzZSwic3Vud2VsbF9uZWNrX3NjcnllciI6ZmFsc2UsIm1hbmFfZXRjaGVkXzRzZXQiOmZhbHNlLCJtZXRhX2dlbSI6MzQyMjAsInRyaW5rZXQxIjozMDYyNiwidHJpbmtldDIiOjM4MjkwLCJpbm5lcnZhdGUiOjAsIm1hbmFfdGlkZSI6ZmFsc2UsImJsb29kbHVzdCI6dHJ1ZSwicG93ZXJfaW5mdXNpb24iOmZhbHNlLCJzeW1ib2xfb2ZfaG9wZSI6ZmFsc2UsIm1haW5fcm90YXRpb24iOjAsInJlZ2VuX3JvdGF0aW9uIjowLCJyZWdlbl9tYW5hX2F0IjoxMCwicmVnZW5fc3RvcF9hdCI6MjUsInJlZ2VuX2FiX2NvdW50IjozLCJhYl9oYXN0ZV9zdG9wIjowLCJmaXJlX2JsYXN0X3dlYXZlIjpmYWxzZSwiY2NfYW1fcXVldWUiOmZhbHNlLCJjY19hbV9yZXBlYXQiOmZhbHNlLCJiaXNfYXNodG9uZ3VlIjpmYWxzZSwidHJpbmtldDFfdCI6WzIwLDAsbnVsbCxudWxsXSwidHJpbmtldDJfdCI6WzQwLDAsbnVsbCxudWxsXSwiYXJjYW5lX3Bvd2VyX3QiOlsyMCxudWxsLG51bGwsbnVsbF0sInByZXNlbmNlX29mX21pbmRfdCI6WzAsbnVsbCxudWxsLG51bGxdLCJpY3lfdmVpbnNfdCI6WzIwLDQwLG51bGwsbnVsbF0sImNvbGRfc25hcF90IjpbNDAsbnVsbCxudWxsLG51bGxdLCJjb21idXN0aW9uX3QiOlsyNSxudWxsLG51bGwsbnVsbF0sImJlcnNlcmtpbmdfdCI6WzQxLG51bGwsbnVsbCxudWxsXSwibWFuYV90aWRlX3QiOlsyMCxudWxsLG51bGwsbnVsbF0sImJsb29kbHVzdF90IjpbMjAsbnVsbCxudWxsLG51bGxdLCJwb3dlcl9pbmZ1c2lvbl90IjpbMSxudWxsLG51bGwsbnVsbF0sImRydW1zX3QiOlsyMCxudWxsLG51bGwsbnVsbF0sImlubmVydmF0ZV90IjpbbnVsbCxudWxsLG51bGwsbnVsbF0sInBvdGlvbl90IjpbMSwwLG51bGwsbnVsbF0sImNvbmp1cmVkX3QiOlsxLDAsbnVsbCxudWxsXSwic3ltYm9sX29mX2hvcGVfYXQiOjAsImV2b2NhdGlvbl9hdCI6MCwiZXZvX3RpY2tzIjowLCJ0YWxlbnRzIjoiaHR0cHM6Ly90YmMud293aGVhZC5jb20vdGFsZW50LWNhbGMvbWFnZS8yNTAwMjUwMzAwMDMwMTUwMzMwMTI1LS0wNTM1MDAwMzEwMDMwMDEiLCJzdGF0cyI6eyJpbnRlbGxlY3QiOjYxNiwic3Bpcml0IjozMDIsIm1wNSI6MTAsImNyaXQiOjE4LjAyOTU2NTIxNzM5MTMwNSwiaGl0Ijo3LjM2OTI1NTE1MDU1NDY3NSwiaGFzdGUiOjEuOTY1NzU3NzY3OTEzNzYwMywic3BlbGxfcG93ZXIiOjEwNDIsInNwZWxsX3Bvd2VyX2FyY2FuZSI6MCwic3BlbGxfcG93ZXJfZnJvc3QiOjAsInNwZWxsX3Bvd2VyX2ZpcmUiOjAsImNyaXRfcmF0aW5nIjozNzgsImhpdF9yYXRpbmciOjkzLCJoYXN0ZV9yYXRpbmciOjMxfSwidG9vbHRpcHMiOmZhbHNlfX0=

**Comment by Cheesehyvel** [comment]
Think you're confusing Skull of Gul'dan with Head Shrunken Head
