### ISSUE TITLE
Feature request for Wrath prep

### ISSUE THREAD

**Issue by Believe82** [Cheesehyvel/magesim-tbc2#82]
Hi I love your sim and the things you have done with.

Could you please add the following feature so we can sim the best gear to go to wrath prepatch (some us as skipping Sunweell or just doing trash clears):
A button that would change set bonus of T5 from 20% to 5%

An alternative would be to add more items to wrath sym, but I imagine that this button I am suggesting is easier to implement.

Many Thanks!

**Comment by Cheesehyvel** [comment]
Biggest change with prepatch new mechanics and talents so this wouldn't really help at all.
Might do a fork of the wotlk sim for level 70 but it's gonna be closer to prepatch.

**Comment by Believe82** [comment]
Ok. Thank you!
